### PR TITLE
Add support for custom subviews in the indicator view

### LINKED ISSUE #46: Unable to add custom views to IndicatorView
I'm not sure if this is a feature you are interested in supporting, but my team maintains an in-house fork to be able to add subviews to the `indicatorView` to support UI that isn't provided. 

In our case, we have a view which behaves as an "underline" for the currently selected index and moves along with the indicator view. If we decide to do something different, we can always just change our custom view to look however we want.

The change required to support this is changing the access modifier of the `indicatorView` property and the `IndicatorView` class to public. Of course, you could always code in accessors like `addSubviewToIndicator` or something similar.

Let me know what you think - if this is something you are interested in supporting, I'd be happy to submit a pull request

### PR DESCRIPTION
**Pull request by amorde**
Closes #46 

Below is a screenshot of what the demo page now looks like

Custom subview example

### CODE REVIEW

**Comment by gmarm** [comment]
Cool, thanks!

**Comment by amorde** [comment]
@gmarm Awesome, thanks for accepting the change!

**Comment by nico75005** [comment]
@gmarm is that possible to create a new tag for this new feature as I thought it was available in the version 0.7 but is not in the end. Cheers

**Comment by gmarm** [comment]
@nico75005 Slight delay but done! https://github.com/gmarm/BetterSegmentedControl/releases/tag/0.8

**Pull request merged**
