### PR TITLE
Add property for indicator border width and color

### PR DESCRIPTION
**Pull request by hsin919**
screen shot 2016-08-04 at 1 58 14 pm
An example above is also added to storyboard.
It's made by new properties `indicatorBorderWidth` and `indicatorBorderColor`

### CODE REVIEW

**Comment by dtp5** [comment]
+1

**Comment by gmarm** [comment]
_Apologies for my late response, didn't have much time lately._

Why is a new `UIView` needed for this? Why not simply set the `IndicatorView`'s layer border properties?

**Comment by hsin919** [comment]
hi @gmarm  Thanks for your feedback. The new UIView you mentioned is the `borderView` which is made for the other segments with different border color than the indicator view. For example we can set the indicator border to yellow and other segment's border to red with `borderView`'s help as below.

screen shot 2016-09-15 at 2 18 29 pm

Please feel free to change the variable name if you think it's not easy to understand. Thanks

**Comment by hsin919** [comment]
Hi I just update the master to resolve the conflict. FYI.

**Comment by TheinHtikeAung** [comment]
Thanks for adding the border. Keep it up

**Comment by gmarm** [comment]
The functionality has been added with a simpler implementation with https://github.com/gmarm/BetterSegmentedControl/pull/44.

I'll be closing this.

**Pull request closed without merging**
