### PR TITLE
add announceImmediately property

### PR DESCRIPTION
**Pull request by cannyboy**
It sometimes makes sense to trigger .ValueChanged on tap, rather than wait for the control to slide into place. The announceImmediately property does this.

(please ignore the podfile stuff)

### CODE REVIEW

**Comment by gmarm** [comment]
_Apologies for my late response, I didn't have much time lately._

This indeed makes much sense!!

However there are some things that need to be done first. Pull `master` branch to resolve conflicts and revert all the changes in unnecessary files and push again. The only files changed should be the control and view controller files. Also, instead of adding a new control as an example to showcase the change, edit the first example ("Lights on / off").

If you're not up for it just close this PR and I'll implement this myself. Cheers.

**Comment by cannyboy** [comment]
ok, i'll see if i can do that

**Comment by cannyboy** [comment]
https://github.com/gmarm/BetterSegmentedControl/pull/26

**Comment by gmarm** [comment]
Merged in https://github.com/gmarm/BetterSegmentedControl/pull/26.

**Pull request closed without merging**
